### ISSUE TITLE
Doesn't seem to do anything on VSCode - Insiders 1.8.0

### ISSUE THREAD

**Issue by rangedsp** [swyphcosmo/vscode-spellchecker#17]
I hope I'm not doing something very stupid, but I couldn't get this plug in to work.

Steps:

1. Install this using the extensions pane
2. Open .md file
3. Type gibberish, nothing seems to happen

If I open the command palette and tell it to create a settings file, it says *command 'spellchecker.createSettingsFile' not found*, maybe that's related?

**Comment by darkmattercoder** [comment]
This applies for me, too.

The extension does not seem to work at all.
I'm on Windows 7 with VsCode 1.7.1

I created a Settings file by hand as well as trying to put the settings in the workspaces settings file.

Both variants do not make it work.

I also noticed that the settings file creation failed with the error from @rangedsp

**Comment by swyphcosmo** [comment]
@rangedsp I was only able to reproduce this issue on a folder that I don't have write permission. Do you have permission to the folder that you're selecting as your workspace?

Are you able to manually create, modify, and save files within your workspace?

Is the path a network path? I have seen some people talking about weird behavior when accessing folders on a networked drive.

What version of the extension, VSCode, and OS are you using? I tested on Windows 10 and Ubuntu 14.04 with both the stable 1.7.1 and Insider 1.8.0 releases. 

There was a small behavior change which might account for you not seeing updates. I found that many people would experience crashes when typing quickly into a file which contains a lot of errors. In order to help with this, I implemented interval checking. The default is 5 seconds. After typing the first letter, the extension will wait 5 seconds before checking the file again. You can disable this in the settings file when you get it to work. 

@devjb Did you reload VSCode after manually creating the settings file? The extension doesn't process changes to this file after loading.

**Comment by darkmattercoder** [comment]
I tried it with the insiders build as well, with a couple of fresh installs, all workspaces being folders where no restrictions exist. Extension does not work and the auto-creation of a settings file always fails with *command 'spellchecker.createSettingsFile' not found*

Can I somehow debug, what is causing that error, to get new hints?

**Comment by swyphcosmo** [comment]
So far, I haven't figured out how to access the extension in a normal workspace. You will need to do the following:
* clone the repository
* run `npm install` to install all the typescript dependencies
* open the repository in VSCode
* open `src/features/SpellCheckerProvider.ts`
* set a breakpoint at [line 89](https://github.com/swyphcosmo/vscode-spellchecker/blob/master/src/features/SpellCheckerProvider.ts#L89)
* press 'F5' to debug the extension
* open a workspace in the new editor
* try creating a settings file

This will trigger the breakpoint, and you'll be able to step through the code to see what's going on. I've had some issues with node not responding when debugging, so you might have better luck writing variables to the console to inspect them.

Please let me know what you find out or if you need any additional help. This problem seems to be happening to several people, and since it's not happening to me, it's impossible for me to fix it.

**Comment by swyphcosmo** [comment]
@devjb In VSCode, go to Help -> About. What version of node does it show?

**Comment by swyphcosmo** [comment]
In addition, I've just uploaded a patch release (v1.2.3) to provide more output during the configuration file creation process. Hopefully, this will help.

As an example, this is the output I received when trying to create a config file in a directory which I do not have write access to:

```
Spellchecker now active!
Spell checker configuration file not found
Creating file 'c:\Program Files (x86)\gs\.vscode\spellchecker.json'
Saving spell check configuration
c:\Program Files (x86)\gs\.vscode
Error: EPERM: operation not permitted, mkdir 'c:\Program Files (x86)\gs\.vscode'
    at Error (native)
    at fs.mkdirSync (fs.js:922:18)
    at Object.exports.wrapFsWithAsar.fs.mkdirSync (ELECTRON_ASAR.js:665:16)
    at Function.sync (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\node_modules\mkdirp\index.js:71:13)
    at SpellCheckerProvider.saveWorkspaceSettings (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\out\src\features\SpellCheckerProvider.js:486:24)
    at SpellCheckerProvider.createSettingsFile (c:\Users\swyph\Documents\Gitlab\VSCode\SpellCheck\vscode-spellchecker\out\src\features\SpellCheckerProvider.js:63:18)
    at t.$executeContributedCommand (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:25694)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:10:10602)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:21356)
    at p (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:7:22033)
```

Normal operation would provide output like this:

```
Spellchecker now active!
Spell checker configuration file not found
Creating file 'c:\Users\swyph\Downloads\Books\.vscode\spellchecker.json'
Saving spell check configuration
c:\Users\swyph\Downloads\Books\.vscode
```

**Comment by TimMensch** [comment]
I also have no spell check. This is true in all spell check extensions I've tried, which is odd, but might be a hint. It also happens on two different computers, and in multiple project folders, though the VS Code configuration is shared between the computers.

Given the latter as a hint, I tracked down the issue, at least for me: You're trying to read settings.json directly, without stripping comments from it. If I leave even a single comment in the middle of the settings.json file, it will crash the spell checker on startup, and I'll get no spell checking at all. Given it breaks all the spell checkers, I bet that they all were forked off of code that does the same thing.

Add a `// comment` in the middle of settings.json and I bet you'll be able to reproduce the issue. I'm betting there's a standard interface for getting the loaded settings from VS Code that you should be using instead, though I haven't actually looked at your code.

**Comment by rangedsp** [comment]
I'm on Windows 10 Pro Insider Preview, build 14965.1001

How do I see the output? Can you repo this error?
![image](https://cloud.githubusercontent.com/assets/4970707/20576081/1d0e4b8c-b221-11e6-8c23-f251d8b33089.png)

About page:
![image](https://cloud.githubusercontent.com/assets/4970707/20576086/2514b1cc-b221-11e6-9e04-d17eb748d8f2.png)

These are my other extensions in case they are conflicting with yours
![image](https://cloud.githubusercontent.com/assets/4970707/20576212/e18f0014-b221-11e6-8386-8e20f29635dc.png)

**Comment by darkmattercoder** [comment]
Thanks to @TimMensch for the comment-hint and @swyphcosmo for the howto on debugging, I was able to track this down. Please have a look at the pull request.

**Comment by swyphcosmo** [comment]
I just merged #20 from @devjb and released a patch version 1.2.4 to the marketplace. Please check it out, and let me know if you're still having problems with the extension.

**Comment by rangedsp** [comment]
@swyphcosmo still no luck, but I've turned on the dev console, and here are the errors:
![image](https://cloud.githubusercontent.com/assets/4970707/20667864/6dfc9686-b5d0-11e6-84c9-0f0476458956.png)

looks like it's missing settings.json, could be a bug with vs code itself?
'C:\Users\Jonny\AppData\Roaming\Code\User\settings.json'

**Comment by darkmattercoder** [comment]
I think that code will only create that file if you have some global settings already. Try to put one empty file in %appdata%

**Comment by rangedsp** [comment]
I may have found the problem, the folder that VS Code Insiders create inside %appdata% is **Code - Insiders**, whereas the error says it's looking for **Code**.

Could there have been some hardcoded paths somewhere?

**Comment by swyphcosmo** [comment]
That's the problem. There are hard coded paths because I had some issues with VSCode giving the correct path to the settings file. I will get this fixed and push an update this evening.

**Comment by swyphcosmo** [comment]
Just pushed version 1.2.5. Let me know if it fixes your problem.

**Comment by rangedsp** [comment]
Working now, thanks so much!
