### ISSUE TITLE
User-level spellchecker.json

### ISSUE THREAD

**Issue by borekb** [swyphcosmo/vscode-spellchecker#38]
Spell checking settings can be stored to user `settings.json` with the `spellchecker.` prefix but I would find it more convenient if I could just move `spellchecker.json` from workspace folder to my user settings folder and be done with it. You extension even seems to pick up value from user settings folder but when I'm adding new words to the dictionary, it creates a `.vscode/spellchecker.json` file again.

The reason is that I synchronize my settings.json with a Sync Settings extension to a Gist and I don't want to re-upload that file every time there's a new word in my custom dictionary which is quite often.

Nice extension btw!

**Comment by swyphcosmo** [comment]
If you use the command "Always Ignore" instead of "Add word to dictionary", the word will be added to the `settings.json` file which already gets synced with Sync Settings.  I only just started using Sync Settings myself, but I think there's a way to automatically sync an additional file such as the spellchecker.json.
