### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by ardan-bkennedy** [swyphcosmo/vscode-spellchecker#4]
I have re-installed this several times. I am running on the latest version of vscode and trying to edit a markdown file. Any possible suggestions on what could be wrong?

**Comment by swyphcosmo** [comment]
Weird. I'm running the newest version of vscode too. Let's see if we can figure this out.

How big is your Markdown file?  It does take a while to parse and check very large files. Would you be able to send me a copy of this file to test?

Does it work on a new file?  After starting vscode, it will take a few seconds to load the dictionary. Try giving it a minute or so, then see if it corrects you as you type.

I do have debug output built into the extension, but it's just using `console.log` statements that seem to get eaten up unless you're debugging the extension. That's an option if you want to clone this repo, open the root directory in vscode. In `src/features/SpellCheckerProvider.ts`, you can change the variable on line 9 to read as `let DEBUG:boolean = true;`. Then, press `F5` to debug the extension. In the first vscode window, you should see console output. 

If debugging the extension isn't an option, I can try changing the debug commands to use `createOutputChannel` which should show up in the Extension section of the output window.

**Comment by ardan-bkennedy** [comment]
The readme file here: https://github.com/ardanlabs/gotraining

I am adding garbage words but I can't get the checker to show a problem. I know it worked in the past. Let me try a new file.

**Comment by ardan-bkennedy** [comment]
A new markdown file is working. Just this file I have is not.

**Comment by ardan-bkennedy** [comment]
Looks like any file that is called README.md is not being processed

**Comment by swyphcosmo** [comment]
I don't think it's isolated to the filename, but rather the content. In `gotraining/README.md` on line 160, the text `his 'Ultimate Go'` is not being tokenized appropriately by my parser. It's becoming `hisUltimate` and `Go`, the former not appearing in the document. This causes an error in the code that's trying to determine the line number. 

If I changed that text to `his Ultimate Go`, the file did work, but it took 61 seconds to parse. Can you try making that change to see if the extension is works with the file and is just taking a long time to parse?  

In the meantime, I'll debug my tokenizer.

**Comment by swyphcosmo** [comment]
I found the bug, and pushed a fix for it. I couldn't get vscode to check for extension updates manually, so I uninstalled the spell checker, restarted vscode as instructed, then installed it again. Your file still takes a while to parse the first time. I think it's because there are more unique "errors" than most files. Each unique error invokes looking for suggestions for the error, which is computationally expensive. As each error occurs, it's saved into a lookup table to speed up future suggestions. The initial load will take significant time, but each successive edit will go much faster. 

Would you verify that the new version works so that I can close the issue?

**Comment by ardan-bkennedy** [comment]
It is working now!! Thanks
