### ISSUE TITLE
only comment need a spell check

### ISSUE THREAD

**Issue by zzzgit** [swyphcosmo/vscode-spellchecker#45]
hello, is there a way to config this plugin to perform only in comment, but not in code?

**Comment by swyphcosmo** [comment]
Unfortunately, there isn't an easy way to do this as this extension is intended to be used in plain text files instead of source code. I would recommend using the [Code Spellchecker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) plugin which has options to configure spellchecking only in comments.

**Comment by zzzgit** [comment]
thanks a lot
