### ISSUE TITLE
Spell checking only working for part of longer Markdown documents

### ISSUE THREAD

**Issue by jx22** [swyphcosmo/vscode-spellchecker#50]
I love this VSCode extension. Thanks for making it @swyphcosmo! With that said, for as long as I've used it, I've found that the spell checker stops working after a certain point in larger files I'm editing in Markdown. In two Markdown files I currently have open, spell checking issues are only being raised before line 281 and line 306, respectively. I had the "editor.wordWrapColumn" setting set to 100 for Markdown documents, for what it's worth. I've reproduced this issue after disabling all other extensions and the minimap, based on the extension author's [previous input](https://github.com/swyphcosmo/vscode-spellchecker/issues/40#issuecomment-287451575). I'm working on VSCode 1.19.3 for Mac. Thanks again.

**Comment by swyphcosmo** [comment]
@jx22 Glad you're enjoying it!

Does your file have a lot of spelling errors in the file already? There is a limit to the number of errors that vscode will display (or at least there was when I first wrote this extension). The limit is set to 250, and you should see a message in the status bar: https://github.com/swyphcosmo/vscode-spellchecker/blob/master/src/features/SpellCheckerProvider.ts#L443

If you aren't seeing that message, would you be able to provide some sample files so that I can investigate further?

**Comment by jx22** [comment]
@swyphcosmo Oh, wow, interesting. I usually keep the status bar disabled. After I enabled the status bar I did see the "Over 250 spelling errors found!" error show up below a large file. So that's working properly -- indeed there were way more than 250 in my file. Do you think I should file an issue to VSCode at this point?

**Comment by cfjedimaster** [comment]
FYI, new user here, and I'm seeing this issue as well. However, I only have 23 problems reported. In my case, I see some mispellings noted, later in the document, but earlier I have this:

```
this is a miseppell. ten minutess long
```

which is being completely ignored. You can see my entire input here: https://gist.github.com/cfjedimaster/5792f505d5623baf06a9f642df1e8c8b

**Comment by cfjedimaster** [comment]
I was able to get the issue down to a much smaller sample. Consider this input:

```
---
layout: post
title: "Adding Algolia Search to Eleventy and Netlify"
date: "2020-06-24"
categories: ["static sites"]
tags: ["eleventy"]
banner_image: /images/banners/search.jpg
permalink: /2020/06/24/adding-algolia-search-to-eleventy-and-netlify
description: How I added Algolia Search to an Eleventy Site
---

this is a miseppell. ten minutess long
rarellly?

This is the only thing I really found awkward with Algolia. (To be clear, not wrong, just... awkward.) In the Algolia docs, they have a section titled "Building Search UI". 
```

With this, I get one mispelling, Algolia, and only the first instance. If I remove the second paragraph, than all the mispellings in the first paragraph magically show up.

**Comment by cfjedimaster** [comment]
FYI, this only occurs via the Remote WSL2 extension.

**Comment by swyphcosmo** [comment]
Hi @cfjedimaster, 

Thanks for this example. Took a bit of looking, but I did find the issue. 

When processing a file, the extension tries to remove sections that shouldn't be parsed. In this case, it's the yaml config at the top of your file. The regex matches everything between `---` and `---` or `...` because different markdown parsers let you use dashs or dots to terminate the yaml. In the middle, I used `(.|\n)*` to match everything in between. Javascript's regex parser is greedy so it will match everything to the ellipsis in `just... awkward`. 

If you remove the second paragraph, the ellipsis is deleted so only the yaml config is removed. 

If you remove the second instance of `Algolia` in the second paragraph, no errors will be found because the first instance would have been removed from the file. This surfaces an error in the logic that inserts the error/warning underlines. That bit of code will find the first instance of `Algolia` on the full text file, i.e. before word filtering. 

I'll get this problem and a few others fixed up, and try to get a new version released soon.
