### ISSUE TITLE
Constant crashes of the extension

### ISSUE THREAD

**Issue by jmmv** [swyphcosmo/vscode-spellchecker#9]
When I'm editing a Markdown editor with the `vscode-spellchecker` extension enabled, I frequently get the following two errors:

```
Error: from the extension host: channel closed *Close*
Error: Extension host terminated unexpectedly. Please reload the window to recover. *Reload window*
```

From there on, the spellchecker stops working and the only thing I can do is reload the window for it to work again. (Mind you, the live Markdown preview also stops working if it happens to be open, but its presence is not a requirement to trigger this bug.)

This is on VSCode 1.5 on OS X.

I know this bug is not descriptive enough... but I don't know how to get more useful logging data. If you can tell me the process to extract any useful error messages, I'll do that the next time it happens. Filing for tracking now anyway.

**Comment by swyphcosmo** [comment]
I get this as well when I'm opening large files. Would you be able to send me a Markdown file that causes problems so that I can try to fix the issue?

**Comment by swyphcosmo** [comment]
I dug up a few large files to test. The issue isn't only a large file, but a file that has a large number of errors. The suggestion function is very costly. To fix this, I've had the spell checker quit after finding 250 errors. A message is displayed in the status bar when this happens. These changes were just uploaded to `v1.2.0`

**Comment by jmmv** [comment]
I'd need to check with some of my files. I don't recall a ton of red in them... but I mostly write technical articles, so "errors" are common in them. What do you suggest for this?

**Comment by swyphcosmo** [comment]
The crash or unresponsiveness comes from the initial search of the file. The file is searched entirely for errors before any are displayed with red underlines. So if the file is very large or has a lot of errors (I have some source code that gets recognized as plain text at first so a file could have thousands of spelling errors), then this first check will take quite a while. I have had some files that took several minutes to fully check. If the "keep waiting" dialog appeared, I just let it continue rather than reopening the window. On each successive check, the previous errors are stored for reference and are used rather than using the costly word suggestion function. With the new changes, the checking should not take nearly as long because the spell checker will escape out of the search after 250 errors are found.

Also with the latest update, words added to the dictionary are written either to your user or workspace settings. So if you have technical terms that are used often, you can add these to the dictionary or ignore list and that will speed up the checking process.

Hope this helps.

**Comment by jmmv** [comment]
Aha, thanks for the explanation and the fix. I'll get back to this bug if I encounter the problem again, but hopefully not!
